eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka

server:
  port: 8020

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer


      emptyCart:
        group-id: emptyCart
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      reviewNotification:
        group-id: emptyCart
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      register:
        group-id: register
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      login:
        group-id: login
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ffa86d69ed128e
    password: 08062f79ed76dc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



# Logging level
logging:
  level:
    root: INFO

# Logstash appender
logstash:
  enabled: true
  appender:
    destination: ${LOGSTASH_HOST}:${LOGSTASH_PORT}

#  Actuator endpoints exposure
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true