eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka

server:
  port: 8060


spring:
  application:
    name: controller-service
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer