eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false

server:
  port: 8761

spring:
  application:
    name: discovery